[opener]
text = [
    { run = 'nvim "$@"', block = true, for = "unix" },
]
video = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
]
audio = [
    { run = 'mpv --no-video "$@"', block = true, for = "unix" },
]
image = [
    { run = 'vimiv "$@"', orphan = true, for = "unix" },
]
pdf = [
    { run = 'zathura "$@"', orphan = true, for = "unix" },
]

[open]
rules = [
    { mime = "text/*", use = "text" },
    { mime = "application/json", use = "text" },
    { mime = "application/x-ndjson", use = "text" },
    { mime = "application/xml", use = "text" },
    { mime = "application/javascript", use = "text" },
    { mime = "application/x-javascript", use = "text" },
    { mime = "application/typescript", use = "text" },
    { mime = "application/x-sh", use = "text" },
    { mime = "application/x-shellscript", use = "text" },
    { mime = "application/toml", use = "text" },
    { mime = "application/yaml", use = "text" },
    { mime = "application/x-yaml", use = "text" },
    { mime = "application/x-perl", use = "text" },
    { mime = "application/x-python", use = "text" },
    { mime = "application/x-ruby", use = "text" },
    { mime = "application/x-lua", use = "text" },
    { mime = "application/sql", use = "text" },
    { mime = "inode/x-empty", use = "text" },
    { mime = "image/*", use = "image" },
    { mime = "video/*", use = "video" },
    { mime = "audio/*", use = "audio" },
    { mime = "application/pdf", use = "pdf" },
    { name = "*", use = "text" },
]
