[opener]
video = [
    { run = 'mpv "$@"', orphan = true, for = "unix" },
]
audio = [
    { run = 'mpv --no-video "$@"', block = true, for = "unix" },
]

[open]
rules = [
    { mime = "video/*", use = "video" },
    { mime = "audio/*", use = "audio" },
]
