# NEED TO RUN EVREMAP COMMAND TO IDENTIFY DEVICE NAMES
# /etc/evremap.toml
device_name = "EVISION USB-STDHID Keyboard"
phys = "usb-0000:00:14.0-6/input1"

# Map Delete key to Arrow Left
[[remap]]
input = ["KEY_DELETE"]
output = ["KEY_LEFT"]

# Map Home key to Arrow Up
[[remap]]
input = ["KEY_HOME"]
output = ["KEY_UP"]

# Map End key to Arrow Down
[[remap]]
input = ["KEY_END"]
output = ["KEY_DOWN"]

# Map Page Down key to Arrow Right
[[remap]]
input = ["KEY_PAGEDOWN"]
output = ["KEY_RIGHT"]


# Map Caps Lock to Escape
[[remap]]
input = ["KEY_CAPSLOCK"]
output = ["KEY_ESC"]

# Map Escape to Caps Lock
[[remap]]
input = ["KEY_ESC"]
output = ["KEY_CAPSLOCK"]

# Map Right Alt to Right Control
[[remap]]
input = ["KEY_RIGHTALT"]
output = ["KEY_RIGHTCTRL"]


